### ISSUE TITLE
Blue numbers, left of the numbers

### ISSUE THREAD

**Issue by ReneFroger** [xmementoit/vim-ide#1]
First, thanks for sharing your Vimrc. 

I noticed there are blue numbers at the left of your numbers, in your screenshot. I was curious what these numbers mean. I looked into your Bundle map, but I couldn't find any related plugin. Could you tell which plugin it is? 

Thanks in advance!

**Comment by DamZiobro** [comment]
Those are markers (http://www.cs.oberlin.edu/~kuperman/help/vim/markers.html). 
You can use it to mark some important places in code (text) and quickly move between them. 
To set up marker k you are using:
mk 
in normal mode.
To go to marker k you can use:
'k
