### ISSUE TITLE
pyfile not found

### ISSUE THREAD

**Issue by uniserpl** [xmementoit/vim-ide#6]
Hi, great work!

Right after installation vim-ide on Ubuntu 16.04 it was required to install zsh.
I cloned vim-ide at 753aa8276fc89a1cb8e9ca3be5fd1bae9852ede0
I have installed Python.
python --version
Python 2.7.12 :: Anaconda 4.2.0 (64-bit)
But...
Обнаружена ошибка при обработке[Processing error detected] /home/user/.vim/bundle/Omnisharp/plugin/OmniSharp.vim:
строка[line]   11:
E319: Извините, эта команда недоступна в данной версии[Sorry, this command is not available in this version]: pyfile /home/user/.vim/bundle/Omnisharp/python/OmniSharp.py

**Comment by DamZiobro** [comment]
Hi,
 In terms of zsh, you are right. As I am using zsh daily, I changed it in the vimrc file. If you prefer to use bash, you can do following change in your $HOME/.vimrc file:
-  set shell=/bin/zsh 
+ set shell=/bin/bash

In terms of OmniSharp.py - I will need to check it in details. 
For now if you don't use C# with your vim-ide I recommend quick fix - removing OmniSharp:
rm -rf $HOME/.vim/bundle/Omnisharp 

Enjoy !
