### ISSUE TITLE
dnf support?

### ISSUE THREAD

**Issue by o-lenczyk** [xmementoit/vim-ide#8]
during the install i have following error:

sudo: apt-get: command not found

is only debian supported?

**Comment by Josheriff** [comment]
I'm not the product developer, but if you inspect the .sh file, (a command scripting file)

You will se this:

```
sudo apt-get --yes install vim vim-gnome

echo -e "Installing ctags"
sudo apt-get --yes install ctags

echo -e "Installing cscope"
sudo apt-get --yes install cscope

echo -e "Installing pip for python-based dpeendencies"
sudo apt-get --yes install pip

echo -e "Installing python dependencies"
sudo pip install pdb pylint
```

so maybe there are a brew command for mac, or whatever other linux distros uses.

**Comment by DamZiobro** [comment]
yes, it may be, but I don't use Mac and don't know that command. Feel free find this command  how to install above tools in MacOS and other OSes. If you will send me the patch I could include it into the repo.
